### ISSUE TITLE
Logo and search bar in header

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-protagonists#1]
# Story

As a user, in order to find attractions I'm interested in, I need to type some value in a text box in the navigation bar at the top of the page, press enter, and see results

# Acceptance Criteria

**Given** a user visits the application
**When** the application renders
**Then** the application logo should appear on the left in a navigation bar

**Given** a user visits the application
**When** the application renders
**Then** a text field should appear in the middle of the navigation bar

**Given** the user types some characters into the search field
**When** user user presses enter
**Then** the areas that contain an attraction, whose name contains the search string, should be outlined with a border

# Technical Information

1. Use regular expressions to match the user's search string with the name of each attraction to find a match. The search string simply must be contained in the attraction name, not just start with.

**Comment by lewiskg** [comment]
* Bootstrap nav bar
* Logo present on left side of nav bar
* Search field in center of nav bar

![untitled diagram](https://user-images.githubusercontent.com/30006745/32136287-8cd0339a-bbd0-11e7-862b-65bf0e0918df.jpg)

**Comment by waamber** [comment]
Search bar value:

```
const pressEnter = () => {
  $(document).keypress((e) => {
    if (e.key === 'Enter') {
      let searchText = $('#search-bar').val();
      let search = searchText.replace(/\s/g, '%20');
      ***call search function??***
    }
  });
};
```

Search value **contained** in attraction name.
When name matches area, border will be added.

**Comment by lewiskg** [comment]
*  The areas that contain an attraction, whose name contains the search string, should be outlined with a border.
![untitled diagram1](https://user-images.githubusercontent.com/30006745/32136406-ecc6df36-bbd2-11e7-957e-99f10c8eb4c5.jpg)

**Comment by waamber** [comment]
* Search bar input id="search-bar" placeholder="Search..." NO FORM TAG!!!
* event pull input and passes to function 

```
const attractionArea =(searchInput)=>{
          attraction name contains searchInput, gets attractions.area_id and matches areas.id
         puts border around area (add border class)
}
```

* id of each card will be the area name

**Comment by waamber** [comment]
* All database calls should be promises.
