### ISSUE TITLE
Project Deployed to Firebase

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-protagonists#13]
# Story

As a project manager, when I see the final product, I would like it to be served from firebase.com

# Acceptance Criteria

**When** the team demos
**Then** they should be hitting the firebase.com deployed url NOT localhost

**Comment by cmurnick** [comment]
The first time you deploy a specific project:
- firebase login
- firebase init

**Comment by cmurnick** [comment]
npm install grunt-contrib-copy --save-dev
npm install grunt-contrib-clean --save-dev

**Comment by cmurnick** [comment]
Remove node_modules from firebase ignore file.
Check firebase rules.
Check that you have all files you need.
