### ISSUE TITLE
User should be able to see all attractions in an area

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-protagonists#3]
# Story

As a user, in order to explore attractions near me, I need to highlight an area of the park and see all attractions in it

# Acceptance Criteria

**Given** user wants to see the attraction list of an area
**When** the user clicks on an area
**Then** all attraction names assigned to that area should be listed in the left 30% of the screen
**And** the attraction type should be in parenthesis next to the name
**And** the name should be a hyperlink

**Comment by lewiskg** [comment]
* User clicks an area
* All attractions in that area appear in a panel on the left
* All attractions must be hyperlinked and contain the type in parenthesis

![untitled diagram3 copy](https://user-images.githubusercontent.com/30006745/32201155-5934e84e-bda3-11e7-9e10-c4440a3afcc8.jpg)

**Comment by waamber** [comment]
Matching:
Areas to attractions 
```areas.id === attractions.area.id ```
Attractions to attraction types
```attractions.type.id === attraction_types.id```

**Comment by waamber** [comment]
List of attractions:
Details should only display when selected. (some cool slide down container)

**Comment by waamber** [comment]
Event listener- on click it grabs specific area card
```
 $('body').on('click', '**areacard**', (e) => {
    let parent = **e.target.closest('**areacard id**');
   * call clear function
   *call function to print attractions to panel
}
```

**Comment by lewiskg** [comment]
Card on click:
* Event listener function gets id of area and passes it to findAttractions(area_id)
* findAttractions() will search an "attractions array" and match the attraction with its area through the area_id and push the attraction to an array that will be passed to printToLeftMenu(array)
* printToLeftMenu() will print the list of attractions in the left menu div
* Each attraction should be wrapped in div element with its associated description also wrapped in a div element
* The id for the attractions will be 'id="attraction-i", where i=0,1,2,3,4....
* The id for the associated  will have an 'id="description-i", where i=0,1,2,3,4....
