### ISSUE TITLE
User should be able to see attraction details

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-protagonists#4]
# Story

As a user, in order to see attraction details or event times, I need to be able to select an attraction and see all available information about it

# Acceptance Criteria

**Given** the user has clicked on an area
**When** the user clicks on a specific attraction's hyperlink
**Then** the description of the attraction, and/or its hours of operation must be displayed directly beneath the hyperlink, and before the next one
**And** any previously displayed attraction details must disappear

**Comment by lewiskg** [comment]
* When an attraction hyperlink is clicked, a description of the attraction, and/or its hours of operation must be displayed directly beneath the hyperlink
* The info must be displayed before the next attraction hyperlink
* Any previously displayed attraction details must disappear

![untitled diagram4](https://user-images.githubusercontent.com/30006745/32204267-45d7b5de-bdb6-11e7-8a2e-cd3c76b99fce.jpg)

**Comment by waamber** [comment]
When selected details should dropdown. When another attraction is selected, previous attraction details should be hidden and new selection be displayed. 

Take into account that some attractions have times and some don't. Will need an if statement for those with time, or else attractions without times will be undefined.

**Comment by lewiskg** [comment]
Event listener on attraction links in left menu.
* Function called in the event listener should get the number in the id of the attraction and then call a function to remove the "hide" class from the associated description div
Example:
```<div id="attraction-0"> .... </div>
<div id="description-0" class="hide"> .... </div>
```
* The same function should also apply the "hide" class to any visible description div
