### ISSUE TITLE
User must see copyright information

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-protagonists#5]
# Story

As a user, in order to know when the content was last updated, I need to see the date of the copyright

# Acceptance Criteria

**Given** user visits the application
**When** the page is rendered
**Then** there should be a copyright notice in a footer element with the current year and today's date.

**Comment by lewiskg** [comment]
* There should be a copyright notice in a footer element with the current year and today's date.

![untitled diagram3](https://user-images.githubusercontent.com/30006745/32136713-1bcb8d9a-bbd8-11e7-84be-9bf1fd19b22f.jpg)

**Comment by waamber** [comment]
Moment.js

http://momentjs.com/

Put script tag in html
Include node in Gruntfile.js

**Comment by lewiskg** [comment]
Code snippet for Gruntfile.js
```
...
        copy: {
            dev: {
                files: [{
                    expand: true,
                    cwd: "../",
                    src: [
                        "index.html",
                        "db/apiKeys.js",
                        "dist/app.js",
                        "images/*",
                        "vendor/*",
                        "styles/**/*.css",
                        "lib/node_modules/moment/moment.js",
                        "lib/node_modules/bootstrap/dist/css/bootstrap.min.css",
                        "lib/node_modules/jquery/dist/jquery.min.js",
                        "lib/node_modules/bootstrap/dist/js/bootstrap.min.js"
                    ],
                    dest: "../public/"
                }]
            }
        }
    });
...
```

Code snippet for index.html
```
<script src="./lib/node_modules/moment/moment.js"></script>
```
