### ISSUE TITLE
User should be able to see events open at a specific time

### ISSUE THREAD

**Issue by zoeames** [nss-evening-cohort-06/theme-park-protagonists#6]
# Story

As a user, in order plan my trip through the park, I need to be able to see which events are open at a particular hour of the day

# Acceptance Criteria

**Given** the user wants to see all events operating at a specific hour
**When** the user performs a gesture on a time selection element above the park grid
**Then** all attractions that operate at that hour should be listed in the left 30% of the screen
**And** the park location should be in parenthesis next to the name
**And** the name should be a hyperlink

# Technical Resource

1. You can use [Bootstrap Material DatePicker's Time Picker widget](http://t00rk.github.io/bootstrap-material-datetimepicker/) if you like. It 👌

**Comment by waamber** [comment]
Using same dom/writeToDom function as attraction details.
When time is selected, it filters through attractions. Outputs attractions that meet time criteria.

If statement to put park location in parenthesis and hyperlinked next to attraction name. 

Dropdown for times - selected time gets passed through a function that converts it to military time. Compares those to an array of shows that have times. 
 
Array of shows with times should be built and available to call when the page loads.

**Comment by lewiskg** [comment]
![untitled diagram2 2](https://user-images.githubusercontent.com/30006745/32202813-3cefd248-bdad-11e7-8a28-5b49f1abdb26.jpg)
